apiVersion: v1
kind: Service
metadata:
  name: web1-service
  labels:
    app: web1
spec:
  selector:
    app: web1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009
